name = "aiva"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["0 19 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "aiva-db"
database_id = "3e660ebf-11b1-47c3-b2c8-752d039dd7dc"

[[kv_namespaces]]
binding = "SESSIONS"
id = "d9d04ee275024e2a9cbfcea9da7a13d4"

[vars]
# GEMINI_API_KEY is stored as a secret via `wrangler secret put GEMINI_API_KEY`
